### ISSUE TITLE
Split Mathigon-related tasks to track them individually

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#1275]
A lot of effort is being put into tasks such as #1189. They require coordination of multiple moving pieces ranging from tracking, widget integration, conversions... Let's split them to individually map and track these efforts.

**Comment by vabarbosa** [comment]
tasks include
- [ ] Jupyter Notebook conversion to Mathigon format: https://github.com/Qiskit/qiskit.org/issues/1342
- [ ] implement progress tracking: https://github.com/Qiskit/qiskit.org/issues/1344
- [ ] integrate Vue components/widget: https://github.com/Qiskit/qiskit.org/issues/1343
