### ISSUE TITLE
Implement header section of the Seminar Series page

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1285]
Create header of the Seminar Series page as designed here: https://www.figma.com/file/nqFBhDOUq6Dknbw9pM92AE/1263-individual-event-pages?node-id=0%3A1

<img width="936" alt="Screenshot 2021-01-08 at 15 47 04" src="https://user-images.githubusercontent.com/22047320/104028239-c7a94380-51c8-11eb-9f83-1c56a0491bbf.png">

This screenshot is from a still not finalised version of the design, so small details like wording or the images being displayed may still change, but the general idea is already well defined.

### Tasks:

- [x] Create general layout of the header including elements on the left part
- [x] Create "up next" card
- [x] Clarify how to retrieve structured data for the "up next" card
