### ISSUE TITLE
Update content of the "Helpful Resources" section in the new Textbook landing page

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1448]
Once we have the content for the "Helpful Resources" section in the new Textbook landing page, we need to update it.

### Tasks:

- [x] Wait for #1447 to be done
- [x] Define final content (copy and links)
- [x] Update content
- [x] Add "segments" for link events tracking
