### ISSUE TITLE
Update content of the "Start Learning" section in the new Textbook landing page

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#1453]
Once we have the content for the "Start Learning" section in the new Textbook landing page, we need to update it.

### Tasks:

- [x] Wait for #1435 to be done
- [x] Define final content (copy and links)
- [x] Update content
- [x] Add "segments" for link events tracking
