### ISSUE TITLE
As a textbook visitor, I want to see the chapter index so that I can quickly view and skip to different parts within a page.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1802]
- [x] chapter index added to left side panel - [#1820](https://github.com/Qiskit/qiskit.org/issues/1820)
- [x] auto-generated chapter index based off of header titles - [#1822](https://github.com/Qiskit/qiskit.org/issues/1822)
- [x] highlights currently viewed section - [#1809](https://github.com/Qiskit/qiskit.org/issues/1809)
- [x] section highlights changes as user scrolls through the page - [#1809](https://github.com/Qiskit/qiskit.org/issues/1809)
- [x] sections are clickable and when clicked users jump too the beginning of clicked section - [#1810](https://github.com/Qiskit/qiskit.org/issues/1810)

**Comment by JRussellHuffman** [comment]
Figma file for this user story: https://www.figma.com/file/WbSzQJbyjP85Jh8o0oFw5W/1802-in-page-index?node-id=0%3A1

**Comment by lerongil** [comment]
Awesome work. This is done.
