### ISSUE TITLE
As a textbook visitor, I want to explore the learning material seamlessly from any spot in my learning journey.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1803]
Acceptance Criteria:

- [x] "browse all content" (the mega menu/mega dropdown done in #1466) is available from any page #1807 
- [x] the user can filter the mega menu by title #1808 
- [x] entering some text will display all the titles containing that text #1808
- [x] entering several words (separated by blanks) will display all the titles containing at least one of the words #1808
- [x] consistent with home page "browse all content" experience 
- [x] selections open up in a new tab

**Comment by techtolentino** [comment]
@JRussellHuffman - 

**Question:** how does this expected behavior work in conjunction with the content hidden behind the 'reveal all' interaction? If a user expects to be taken to a section that's hidden - do we reveal first, then jump to section?

**Comment by JRussellHuffman** [comment]
@techtolentino great question. not sure. That would be one way to handle it, and not a bad option.

**Comment by JRussellHuffman** [comment]
If we go that rought, it may be worth adding some indication in the index as to what content is currently being shown, and what is hidden.

**Comment by JRussellHuffman** [comment]
Based on discussion during sprint planning, lets have all content revealed by default for now.

**Comment by JRussellHuffman** [comment]
Figma file for this user story: https://www.figma.com/file/zr4RPOb7q8FNae8XooYizh/1803-explore-learning-content?node-id=0%3A1

**Comment by y4izus** [comment]
@lerongil , @delapuente . @JRussellHuffman , could you clarify this acceptance criteria? "consistent with home page "browse all content" experience". I'm not sure what it's referring to

**Comment by y4izus** [comment]
yes! thank you Russell!

**Comment by lerongil** [comment]
This looks great. Thank you team :)
