### ISSUE TITLE
Share the Browse all dropdown component between qiskit.org and platypus

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#1817]
### Tasks:

- [x] Create reusable component: https://github.com/qiskit-community/qiskit-vue/issues/13
- [x] Use component in Qiskit.org: https://github.com/Qiskit/qiskit.org/pull/2025
- [x] Use component in Platypus: https://github.com/qiskit-community/platypus/pull/82
