### ISSUE TITLE
As a product manger, I want to be able to view textbook analytics, so that I can better improving the learning experience.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1847]
Acceptance Criteria: 

- [x] Hotjar correctly instrumented on all learn pages 
- [x] Segment instrumented for search to track words searched and pages clicked #1857 #1859
- [x] CTAs instrumented with Segment #1861
- [x] # of Multiple Choice Questions viewed and # of Multiple Choice Questions completed #1858 #1860
- [x] Multiple Choice Questions instrumented so that we can see % of users answering questions correctly #1858 #1860
- [x] Total number of exercises completed  #1858 #1860

**Comment by lerongil** [comment]
Acceptance criteria point 1 is related to #1851

**Comment by lerongil** [comment]
This user story is finished. Thanks to the team for your efforts. We did find a bug which is described here #1851. We will add this to the backlog.
