### ISSUE TITLE
Redirect URLs in Platypus 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1919]
- [x] https://qiskitorg-git-feature-textbook-demo-qiskit.vercel.app/textbook-demo should be qiskit.org/textbook-beta #1930
- [x] learn.qiskit.org should redirect to qiskit.org/textbook-beta #1931
- [x] if a user visits learn.qiskit.org/textbook, the user should be taken to qiskit.org/textbook-beta #1939

**Comment by lerongil** [comment]
LGTM!
