### ISSUE TITLE
Update qiskit.org/learn with links to textbook-beta 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#1924]
- [x] Replace Qiskit Textbook link from qiskit.org/textbook to qiskit.org/textbook-beta #1932
- [x] Replace Qiskit Textbook Chapters 1 - 3 Title with Introduction Course #1932
- [x] Replace Qiskit Textbook Chapters 1 - 3 https://qiskit.org/textbook/ch-states/introduction.html with https://qiskit.org/textbook-beta/course/introduction-course #1932 
- [x] Updates cards content #1932

**Comment by y4izus** [comment]
@lerongil , @JRussellHuffman , I need more info here:
- The copy or the image on the card for the textbook should change? Right now we have:
<img width="648" alt="Captura de pantalla 2021-06-30 a las 12 11 11" src="https://user-images.githubusercontent.com/17231966/123943261-44f58a00-d99c-11eb-836a-f21f2e69f6c2.png">

- By doing the change from textbook 1-3 to introduction course, we need to change copy and image. What we have right now:
<img width="650" alt="Captura de pantalla 2021-06-30 a las 12 12 18" src="https://user-images.githubusercontent.com/17231966/123943411-6bb3c080-d99c-11eb-8c9e-2f23698dc76c.png">

suggestions to update description, cta and image?

**Comment by JRussellHuffman** [comment]
Updated the thumbnail images and put them here: https://www.figma.com/file/PDbN8wcg5WteWVvinjAEUv/qiskit.org-main-file?node-id=3429%3A45121. Let me know if you have any issues with them.

I think @lerongil is better suited to update the copy than me.

As for the order of the cards, I would recommend:
1. Textbook
2. Intro Course (replacing ch 1-3)
3. Coding with Qiskit
4. Qiskit Medium
5. Qiskit Tutorial
6. Introduction to Quantum Computing and Quantum Hardware

**Comment by lerongil** [comment]
Copy for Qiskit Textbook: The Qiskit Textbook is a free digital open source textbook that will teach the concepts of quantum computing while you learn to use Qiskit. 

CTA: Read the textbook

----- 

Copy for Intro Course: This introduction course is around 3 hours long and will take individuals from all backgrounds through a linear path of content that begins at the atoms of computation and ends at Grover's algorithm. 

CTA: Take the course

**Comment by lerongil** [comment]
Thank you @y4izus and @techtolentino!
