### ISSUE TITLE
As a learner, I want to be able to revisit the 2021 summer school content via the Qiskit Textbook so that I can learn the material even if I wasn't present at the summer school.

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2146]
- [x] a new block on the Qiskit Textbook home page. (this will be similar to the cards currently on the home page. Final designs to come from the design team) https://github.com/Qiskit/qiskit.org/issues/2154
- [x] a new overview page for the summer school content (this will be similar to the intro course overview page. Final designs to come from the design team) https://github.com/Qiskit/qiskit.org/issues/2153
- [x] summer school notebooks added to learn.qiskit.org (this will be created by the edu team and should not require development effort) https://github.com/Qiskit/qiskit.org/issues/2152
- [x] #2165

**Comment by lerongil** [comment]
Awesome job team. This looks great and will be very helpful to the community.
