### ISSUE TITLE
As a challenge organizer, I want to be run a Quantum Challenge so participants can learn and gain experience with quantum computing and Qiskit

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/qiskit.org#2205]
- [x] Update challenge dashboard/landing page: https://github.com/Qiskit/qiskit.org/issues/2204
- [x] Update challenge grading service: https://github.com/Qiskit/qiskit.org/issues/2203
- [x] Update challenge grader client: https://github.com/Qiskit/qiskit.org/issues/2202
