### ISSUE TITLE
Update to Node v16

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2275]
Following the discussion in https://github.com/Qiskit/qiskit.org/discussions/2269, we need to upgrade to Node v16.

### Tasks:

- [x] Update Qiskit-Vue - https://github.com/qiskit-community/qiskit-vue/pull/36
- [x] Update Qiskit-Web-Components - https://github.com/qiskit-community/qiskit-web-components/pull/29
- [ ] Update Qiskit.org
- [x] Update Platypus - https://github.com/Qiskit/platypus/pull/1783

**Comment by y4izus** [comment]
Node is on LTS 18.12, we should check if we can update to the latest version
