### ISSUE TITLE
GDPR and Export Control Compliancy Checklist

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit.org#2303]
Per user story #1972, we will need to review the authentication and authorization service we provide to users via oauth. This might include:

- [] Review data collected 
- [] Review data stored and length of time stored 
- [] Review what to do with data after deletion request
