### ISSUE TITLE
Learn content: Add Cards and Links for "On other platforms" section

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2583]
As part of the Learn content updates, we'll also need to add Cards that link to their respective platforms (YouTube and Medium). This issue is for adding these cards, assets, and links to the current `/textbook-beta` page, under the "On other platforms" section.

[Design file here](https://www.figma.com/file/X9p7omJAZncvDpg2IJLS6J/407-learn-page-migration?node-id=10%3A332)

**Tasks**
- [x] Add "On other platforms" section to the `/textbook-beta` page
- [x] Add card for YouTube 
- [x] Add card for Medium

![Screen Shot 2022-05-11 at 11 30 09 AM](https://user-images.githubusercontent.com/6276074/167921132-04cb96b7-432c-490a-8df7-7c2ee91734d3.png)

**Comment by Tansito** [comment]
@JRussellHuffman as @techtolentino is showing in the image the description for **Youtube** and **Medium** seems a bit weird (they have the same content as **Summer School**), could you confirm me if that's ok?

**Comment by JRussellHuffman** [comment]
that's an oversite on our part. I'll connect with the team to get better text
