### ISSUE TITLE
As a student learner, I want to discover more information about how to participate in the Qiskit Fall Fest event.

### ISSUE THREAD

**Issue by BrianIngmanson** [Qiskit/qiskit.org#2712]
### Feature description

Hi :)  I'd like to make a page like this (https://qiskit.org/events/summer-school/) to highlight this year's Qiskit Fall Fest, which is a collection of Qiskit events led by student leaders on their local campuses, all happening in October this year. More info on the Fall Fest in general here -- https://medium.com/qiskit/you-are-invited-to-qiskit-fall-fest-2022-af107a50b9da

### Acceptance criteria

- [x] The event page is implemented as requested (Sign-off from @BrianIngmanson and @JRussellHuffman)

### Tasks

- [x] https://github.com/Qiskit/qiskit.org/issues/2786
- [x] https://github.com/Qiskit/qiskit.org/issues/2787

### Additional context

I'd like to use this page as both a public-facing overview page explaining what the Fall Fest is, but also to serve as a landing page that we can link to all the individual campus events from.

**Comment by techtolentino** [comment]
Assigning myself to this, but it'll be handled by @leenatantawy
