### ISSUE TITLE
As a event organizer, I want to host a quantum challenge so that participants can learn and gain experience with quantum computing and Qiskit

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/qiskit.org#2790]
### Background

A quantum challenge is forthcoming which will be taking advantage of our challenge & grading platforms. These platforms need to be updated the  to support the event. 

### Goal

Provide a platform where participants can successfully register and participate in the quantum challenge.

### Acceptance criteria

- [ ] participants able to register for the challenge
- [ ] participants able to access & successfully complete the challenge exercises (during challenge dates)
- [ ] participants able to see their progress through the challenge

### Tasks

**set up**
- [x] coordinate with event organizers & content creators on challenge content/details
- [x] configure & update the grading server with the challenge content
- [x] update grading client for upcoming challenge
- [x] configure & update challenges api with the challenge details

**test**
- [x] deploy grading server, grading client, & challenges api to staging env
- [x] coordinate with event organizers & content creators to test the challenge flow & exercises in staging

**production**
- [x] deploy grading server, grading client, & challenges api to production

**Comment by Tansito** [comment]
Nice work! 👏

**Comment by vabarbosa** [comment]
thank you @alexao8 @memolina2323
