### ISSUE TITLE
Marketing site tasks for Sprint 19

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2800]
### Tasks

- [x] https://github.com/Qiskit/qiskit.org/issues/2802
- [x] https://github.com/Qiskit/qiskit.org/issues/2803
- [x] https://github.com/Qiskit/qiskit.org/issues/2804
- [x] https://github.com/Qiskit/qiskit.org/issues/2806
