### ISSUE TITLE
Marketing site tasks for Sprint 20

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2820]
### Tasks

- [ ] https://github.com/Qiskit/qiskit.org/issues/2801
- [ ] https://github.com/Qiskit/qiskit.org/issues/2805
- [ ] https://github.com/Qiskit/qiskit.org/issues/2807
- [ ] https://github.com/Qiskit/qiskit.org/issues/2808
- [ ] https://github.com/Qiskit/qiskit.org/issues/2809
- [ ] https://github.com/Qiskit/qiskit.org/issues/2810
- [ ] https://github.com/Qiskit/qiskit.org/issues/2811
- [ ] https://github.com/Qiskit/qiskit.org/issues/2812
- [ ] https://github.com/Qiskit/qiskit.org/issues/2813
- [ ] https://github.com/Qiskit/qiskit.org/issues/2814
- [ ] https://github.com/Qiskit/qiskit.org/issues/2815
- [ ] https://github.com/Qiskit/qiskit.org/issues/2816
- [ ] https://github.com/Qiskit/qiskit.org/issues/2817
