### ISSUE TITLE
As a Qiskit developer, I want to have a place to see all the providers, so that I can quickly have an overview of what's the next step after compilation

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#2855]
### Background

As qiskit.org focuses its message around compiling capabilities for any kind of hardware, there is a need to highlight this aspect. Currently, some providers are buried in https://qiskit.org/documentation/partners/ or qiskit.org/ecosystem 

### Goal

Highlight the many providers that Qiskit can connect to.

### Acceptance criteria

 - [x] deploy a qiskit.org/providers site

### Out of scope

 - The scope of the Qiskit Partner Program is out of the scope.
 - The provider section on the documentation menu may eventually need to be removed, but the removal is out of scope for this issue.

### Future of feature

 - One of a kind
 - A workflow for quickly update the code snippet might be needed

### Resources

Initial idea: [qiskit.org_providers.pdf](https://github.com/Qiskit/qiskit.org/files/9868215/qiskit.org_providers.pdf)
Design file: https://www.figma.com/file/libCKS85dBrctor92Iroum/2855-Provider-page?node-id=1%3A2371&t=vj6oDfcLW6odJTPd-1

### Tasks

 - [x] design a qiskit.org/provider site. I created [this Figma page](https://www.figma.com/file/XIgKKCXuH7PzQrdk6CBJTN/qiskit.org%2Fproviders?node-id=0%3A1) as a starting point.
 - [x] come up with description for each provider in the page
 - [x] come up with a short example for each provider in the page
 - [x] have a clear workflow to keep examples up to date (they might be needed to have quick changes, as non-qiskit packages get updated)
 - [x] deploy it

**Comment by 1ucian0** [comment]
- @mtreinish can you help with some of the text and examples?
 - @JRussellHuffman what do you think about the design?

**Comment by JRussellHuffman** [comment]
Broad strokes, I like it. I like that it reuses the overview page design and components. The design could use some clean up, but nothing crazy.

**Comment by JRussellHuffman** [comment]
@1ucian0, I took a stab at cleaning up the original design concept here: https://www.figma.com/file/libCKS85dBrctor92Iroum/2855-Provider-page?node-id=1%3A2371&t=vj6oDfcLW6odJTPd-1

Lets talk about what content goes in each accordion item. I think we can clean it up and a bit for increased legibility.

**Comment by JRussellHuffman** [comment]
Also FYI, I updated the figma link in the description. I started a new file because I think the other wasn't a part of our workspace in figma

**Comment by y4izus** [comment]
Info for devs:

- The idea is to remove the [Overview page](https://qiskit.org/overview/) and to add a Providers page instead
- Updates on top menu (needs an issue on the web-components repo)
  - The link to the Providers page will be near the Documentation link, on its right side
  - The links to Providers and Core will be removed from the Documentation drop-down menu. Here we need to decide if the block will continue having the size of the screen or if we want that block to adjust to the content on the submenu
- The page will reuse the structure of the overview page but removing the Quick Start component
- We will try to follow the same structure inside the accordion components so we can divide content and structure. That will allow them to change the content without asking us for updates.

**Comment by JRussellHuffman** [comment]
content for this page is being worked on here: https://github.com/Qiskit/qiskit.org/pull/2968

**Comment by techtolentino** [comment]
FYI - I'm moving this User Story back to the backlog column since there are smaller tasks in the breakdown of getting this accomplished:

- [x] Setup Provider page and remove Overview page
- [x] Provide json content 
- [ ] Use json content/data in page template and components
- [ ] Use web-components UI Shell w/ new Provider menu item 
- [ ] Launch page
