### ISSUE TITLE
As a qiskit developer/user, I want an index of all the support channels so that I can be more effective in my questions and feedback

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#3021]
### Background

It is getting harder to understand where is the right place to [ask a specific question](https://github.com/Qiskit/feedback/wiki/Communication-Channels-&-Support#qiskit-slack), [provide general feedback](https://github.com/Qiskit/feedback/wiki/Communication-Channels-&-Support#general-feedback), [communicate that the slack invite expired](https://quantumcomputing.stackexchange.com/search?q=slack+link) and so on.

### Goal

Have a guide on to help users with questions and support to find the right channel so they can get answers quicker.

### Acceptance criteria

- [ ] design and deploy qiskit.org/support
- [ ] make it accessible from the top menu at root level

### Tasks

- [x] Change the QCSE link https://github.com/Qiskit/web-components/issues/210
- [ ] Design content for qiskit.org/support page, like a better https://github.com/Qiskit/feedback/wiki/Communication-Channels-&-Support
- [ ] deploy using one of the current webcomponents or design one
- [ ] Change qisk.it/support to qiskit.org/support

**Comment by y4izus** [comment]
@1ucian0 , could we close this?

**Comment by 1ucian0** [comment]
we talked with @javabster about moving this issue to https://docs.quantum.ibm.com/support . So yes, it can be closed.
