### ISSUE TITLE
move non-Qiskit documentation out of qiskit.org/documentation

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit.org#3054]
As we move towards a more strict `qiskit == qiskit-terra`, the non-qiskit projects that are deploying their documentation in  `qiskit.org/documentation/<something>` need to slowly start moving somewhere else. In most cases, that will be `qiskit.org/ecosystem/<something>`.  This affects the following projects:

1. https://qiskit.org/documentation/aer/
2. https://qiskit.org/documentation/rustworkx/
3. https://qiskit.org/documentation/retworkx/
4. https://qiskit.org/documentation/partners/ionq/
5. https://qiskit.org/documentation/partners/aqt/
6. https://qiskit.org/documentation/experiments/
7. https://qiskit.org/documentation/nature/
8. https://qiskit.org/documentation/optimization/
9. https://qiskit.org/documentation/partners/qiskit_ibm_runtime/
10. https://qiskit.org/documentation/machine-learning/
11. https://qiskit.org/documentation/finance/
12. https://qiskit.org/documentation/partners/mthree/
13. https://qiskit.org/documentation/partners/qiskit_ibm_provider/
14. https://qiskit.org/documentation/partners/qiskit_ibm_experiment/
15. https://qiskit.org/documentation/neko/
16. https://qiskit.org/documentation/metal/
17. https://qiskit.org/documentation/dynamics/

The tasks for each of these projects are the following:

- [X] preserve /ecosystem https://github.com/Qiskit/qiskit.org/pull/3011
- [x] copy current documentation to ecosystem
  - [x] https://qiskit.org/ecosystem/aer/
  - [x] https://qiskit.org/ecosystem/rustworkx/
  - [x] https://qiskit.org/ecosystem/ionq/
  - [x] https://qiskit.org/ecosystem/aqt/
  - [x] https://qiskit.org/ecosystem/experiments/
  - [x] https://qiskit.org/ecosystem/nature/
  - [x] https://qiskit.org/ecosystem/optimization/
  - [x] https://qiskit.org/ecosystem/ibm-runtime/
  - [x] https://qiskit.org/ecosystem/machine-learning/
  - [x] https://qiskit.org/ecosystem/finance/
  - [x] https://qiskit.org/ecosystem/mthree/
  - [x] https://qiskit.org/ecosystem/ibm-provider/
  - [x] https://qiskit.org/ecosystem/ibm-experiment/
  - [x] https://qiskit.org/ecosystem/neko/
  - [x] https://qiskit.org/ecosystem/metal/
  - [x] https://qiskit.org/ecosystem/dynamics/
- [ ] deploy in ecosystem next time https://github.com/Qiskit/qiskit.org/issues/3038
- [x] configure CDN to redirect  (notice that the prefix `qiskit-` can be removed):
  - [x] [`documentation/aer -> ecosystem/aer`](https://qiskit.org/documentation/aer)
  - [x] [`documentation/rustworkx -> ecosystem/rustworkx`](https://qiskit.org/documentation/rustworkx/)
  - [x] [`documentation/retworkx -> ecosystem/rustworkx`](https://qiskit.org/documentation/retworkx/)
  - [x] [`documentation/partners/ionq -> ecosystem/ionq`](https://qiskit.org/documentation/partners/ionq)
  - [x] [`documentation/partners/aqt -> ecosystem/aqt`](https://qiskit.org/documentation/partners/aqt)
  - [x] [`documentation/experiments -> ecosystem/experiments`](https://qiskit.org/documentation/experiments)
  - [x] [`documentation/nature -> ecosystem/nature`](https://qiskit.org/documentation/nature)
  - [x] [`documentation/optimization -> ecosystem/optimization`](https://qiskit.org/documentation/optimization)
  - [x] [`documentation/partners/qiskit_ibm_runtime -> ecosystem/ibm-runtime`](https://qiskit.org/documentation/partners/qiskit_ibm_runtime)
  - [x] [`documentation/machine-learning -> ecosystem/machine-learning`](https://qiskit.org/documentation/machine-learning)
  - [x] [`documentation/finance -> ecosystem/finance`](https://qiskit.org/documentation/finance)
  - [x] [`documentation/partners/mthree -> ecosystem/mthree`](https://qiskit.org/documentation/partners/mthree)
  - [x] [`documentation/partners/qiskit_ibm_provider -> ecosystem/ibm-provider`](https://qiskit.org/documentation/partners/qiskit_ibm_provider)
  - [x] [`documentation/partners/qiskit_ibm_experiment -> ecosystem/ibm-experiment`](https://qiskit.org/documentation/partners/qiskit_ibm_experiment)
  - [x] [`documentation/neko -> ecosystem/neko`](https://qiskit.org/documentation/neko)
  - [x] [`documentation/metal -> ecosystem/metal`](https://qiskit.org/documentation/metal)
  - [x] [`documentation/dynamics -> ecosystem/dynamics`](https://qiskit.org/documentation/dynamics)
- [x] create new sphinx theme for ecosystem projects https://github.com/Qiskit/qiskit_sphinx_theme/issues/311
- [ ] stop deploying on /documentation https://github.com/Qiskit/qiskit.org/issues/3038#issuecomment-1674755994
- [ ]  depend on new theme

**Comment by HuangJunye** [comment]
Moving qiskit-ibmq-provider documentation to its own standalone documentation site is not mentioned here. We can create a separate issue in an appropriate repo. But I just want to mention it here and @Guillermo-Mijares-Vilarino will work on that.

**Comment by 1ucian0** [comment]
> Moving qiskit-ibmq-provider documentation to its own standalone documentation site is not mentioned here. We can create a separate issue in an appropriate repo. But I just want to mention it here and @Guillermo-Mijares-Vilarino will work on that.

For reference https://github.com/Qiskit/qiskit-ibmq-provider/pull/1166

It is not in the list because does not have to be _moved_, it can be created directly in `q.o/ecosystem`.

**Comment by y4izus** [comment]
https://qiskit.org/documentation/partners/qiskit_ibm_experiment/ already redirects to https://qiskit.org/ecosystem/ibm-experiment/, so I've checked the checkbox

**Comment by y4izus** [comment]
These URLs already have the redirections, so I've checked them on the list:

- [documentation/rustworkx -> ecosystem/rustworkx](https://qiskit.org/documentation/rustworkx/)
- [documentation/neko -> ecosystem/neko](https://qiskit.org/documentation/neko)
- [documentation/metal -> ecosystem/metal](https://qiskit.org/documentation/metal)

**Comment by 1ucian0** [comment]
the residual PRs are on non-blocking components.
