### ISSUE TITLE
As a Qiskit Advocate, I would like to highlight my QAMP projects, so that I can promote the work I have completed

### ISSUE THREAD

**Issue by KallieFerguson** [Qiskit/qiskit.org#3055]
### Background

Qiskit Advocates can participate in QAMP, which pairs mentees with mentors on a wide variety of qiskit and quantum related projects. Each mentorship cohort lasts around 3 months, although some QAMP groups have continued their work after the end of an official cohort period. 

### Goal

We want to highlight and celebrate the output of QAMP projects, whether they are a game, published paper, development tool, etc. 

### Acceptance criteria

- [ ] projects from QAMP are displayed on the webpage
- [ ] names of project collaborators 
- [x] ~an image for each project~. Per offline conversations, the image is not needed

### Out of scope

- [ ] which cohort they were in

### Future of feature

- Link collaborators to an Advocate on the Advocate page
- Topic tags to allow users to find projects that are relevant or interest to them

### Resources

- Spring 2021: https://github.com/qiskit-advocate/qamp-spring-21 
- Fall 2021: https://github.com/qiskit-advocate/qamp-fall-21
- Spring 2022: https://github.com/qiskit-advocate/qamp-spring-22
- Fall 2022: https://github.com/qiskit-advocate/qamp-fall-22
- Spring 2023: https://github.com/qiskit-advocate/qamp-spring-23

### Tasks

```[tasklist]
- [x] https://github.com/Qiskit/qiskit.org/issues/3112
- [x] #3192
- [x] #3193
- [x] #3194
- [x] ~#3257~ (see https://github.com/Qiskit/qiskit.org/issues/3257#issuecomment-1563060004)
```

**Comment by GemmaDawson** [comment]
This is fantastic - the only change that I would like is to differentiate between mentors & mentees (and from Spring 23 onwards, we are adding a new type of participant - "Collaborator").

We would also like to consider adding an additional link for some of the projects.

Otherwise we are good to go!

**Comment by JRussellHuffman** [comment]
For showing the QAMP projects on qiskit.org, I think there are 2 main aspects of this
1. showing an overview card before the user clicks into the project
2. showing the actual project

For (1), I think we need a title, description, and URL to the actual project. We could do a picture, if every project has a good image, but I am inclined to make it optional and to use a card similar to what we use on the [ecosystem page](https://qiskit.org/ecosystem/).

For (2), what is the actual project? Is it the PDF from the final presentations? Is it a github repo?

**Comment by y4izus** [comment]
We are not gonna add more features to this repo so we can close this issue
