### ISSUE TITLE
As a qiskit user, I want an improved layout/UI of ecosystem projects, so that I can find important main tier projects more easily

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3229]
### Background

We have received feedback about a lot of different UI related things for the ecosystem page. Mostly people are struggling to find what they are looking for with the current card based layout. This is especially an issue for users looking for the main tier projects (these are the most commonly used projects) and will continue to cause friction in future when the [top menu is  redone](https://github.com/Qiskit/qiskit.org/issues/3169) and most of the links to main tier documentation will be removed.

### Goal

- Users looking for main tier documentation should be able to find it easily
- users should be able to see as many projects in a single view as possible
- users should be able to quickly find a specific project (e.g. with search, sorting, and/or more advanced filtering)

### Tasks

```[tasklist]
- [ ] https://github.com/Qiskit/qiskit.org/issues/2880
- [ ] https://github.com/Qiskit/qiskit.org/issues/2927
- [ ] https://github.com/Qiskit/qiskit.org/issues/3045
- [ ] https://github.com/Qiskit/qiskit.org/issues/3170 (this story maybe should be rewritten as a task)
- [x] #3248
```

<img width="1844" alt="Screenshot 2023-05-17 at 3 28 56 PM" src="https://github.com/Qiskit/qiskit.org/assets/23662430/b50bd17e-b626-43dc-a455-44681910fdb3">
