### ISSUE TITLE
As a dev I want to have more test

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3372]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/qiskit.org/issues/3373
- [ ] https://github.com/Qiskit/qiskit.org/issues/3381
- [ ] https://github.com/Qiskit/qiskit.org/issues/3382
- [ ] https://github.com/Qiskit/qiskit.org/issues/3383
```
