### ISSUE TITLE
As a Qiskit.org maintainer, I want to replace Hotjar with Alchemer, so that I can collect user feedback.

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3434]
We have to stop using Hotjar and start using Alchemer.

Alchemer has different ways to collect feedback and we need to use [Intercepts](https://help.alchemer.com/help/website-intercept) to replace the surveys we have from Hotjar.

**Acceptance criteria**

```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/qiskit.org/issues/3437
- [ ] https://github.com/Qiskit/qiskit.org/issues/3438
- [ ] https://github.com/Qiskit/qiskit.org/issues/3439
```

**Out of scope**
Add Alchemer on the textbook

**Comment by y4izus** [comment]
The three tasks on this issue are done, so we can close it
