### ISSUE TITLE
Bug: broken links in qiskit.org

### ISSUE THREAD

**Issue by paaragon** [Qiskit/qiskit.org#3470]
### Where does the issue happen?

https://qiskit.org

### What is the content issue?

[The last run of the Broken Links workflow](https://github.com/Qiskit/qiskit.org/actions/runs/5716916956) gives us these broken links on each page:

https://qiskit.org/learn/
- [x] id #0c64696060634c7d657f67657822637e6b not found	https://qiskit.org/cdn-cgi/l/email-protection#0c64696060634c7d657f67657822637e6b
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/
- [x] 404	https://docs.nvidia.com/cuda/cuquantum/custatevec/index.html
- [x] id #6f070a0303002f1e061c04061b41001d08 not found	https://qiskit.org/cdn-cgi/l/email-protection#6f070a0303002f1e061c04061b41001d08
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/games-and-demos/
- [x] 404	https://learn.qiskit.org/course/ch-demos/estimating-pi-using-quantum-phase-estimation-algorithm
- [x] id #234b464f4f4c63524a50484a570d4c5144 not found	https://qiskit.org/cdn-cgi/l/email-protection#234b464f4f4c63524a50484a570d4c5144
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/quantum-hardware-circuits/
- [x] id #127a777e7e7d52637b61797b663c7d6075 not found	https://qiskit.org/cdn-cgi/l/email-protection#127a777e7e7d52637b61797b663c7d6075
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/quantum-algorithms-for-applications/
- [x] id #8be3eee7e7e4cbfae2f8e0e2ffa5e4f9ec not found	https://qiskit.org/cdn-cgi/l/email-protection#8be3eee7e7e4cbfae2f8e0e2ffa5e4f9ec
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/prerequisites/
- [x] id #8ae2efe6e6e5cafbe3f9e1e3fea4e5f8ed not found	https://qiskit.org/cdn-cgi/l/email-protection#8ae2efe6e6e5cafbe3f9e1e3fea4e5f8ed
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/quantum-computing-labs/
- [x] id #4c24292020230c3d253f27253862233e2b not found	https://qiskit.org/cdn-cgi/l/email-protection#4c24292020230c3d253f27253862233e2b
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/quantum-hardware-pulses/
- [x] id #147c7178787b54657d677f7d603a7b6673 not found	https://qiskit.org/cdn-cgi/l/email-protection#147c7178787b54657d677f7d603a7b6673
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/documentation/apidoc/providers.html
- [ ] 404	https://fonts.googleapis.com
- [ ] 404	https://fonts.gstatic.com

https://qiskit.org/learn/course/machine-learning-course/
- [x] id #1a727f7676755a6b736971736e3475687d not found	https://qiskit.org/cdn-cgi/l/email-protection#1a727f7676755a6b736971736e3475687d
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/fundamentals-quantum-algorithms/
- [x] id #274f424b4b4867564e544c4e5309485540 not found	https://qiskit.org/cdn-cgi/l/email-protection#274f424b4b4867564e544c4e5309485540
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate
- [x] id #overview not found	https://www.cambridge.org/highereducation/books/quantum-computation-and-quantum-information/01E10196D0A682A6AEFFEA52D53BE9AE#overview

https://qiskit.org/learn/course/quantum-protocols-and-quantum-algorithms/
- [x] 404	http://mmrc.amss.cas.cn/tlb/201702/W020170224608149125645.pdf
- [x] 404	http://mmrc.amss.cas.cn/tlb/201702/W020170224608149940643.pdf
- [x] id #442c2128282b04352d372f2d306a2b3623 not found	https://qiskit.org/cdn-cgi/l/email-protection#442c2128282b04352d372f2d306a2b3623
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/multiple-qubits-and-entanglement/
- [x] 404	http://mmrc.amss.cas.cn/tlb/201702/W020170224608149125645.pdf
- [x] 404	http://mmrc.amss.cas.cn/tlb/201702/W020170224608149940643.pdf
- [x] id #39515c5555567948504a52504d17564b5e not found	https://qiskit.org/cdn-cgi/l/email-protection#39515c5555567948504a52504d17564b5e
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/quantum-states-and-qubits/
- [x] 404	http://mmrc.amss.cas.cn/tlb/201702/W020170224608149125645.pdf
- [x] 404	http://mmrc.amss.cas.cn/tlb/201702/W020170224608149940643.pdf
- [x] 404	https://learn.qiskit.org/course/ch-states/the-atoms-of-computation
- [x] id #88e0ede4e4e7c8f9e1fbe3e1fca6e7faef not found	https://qiskit.org/cdn-cgi/l/email-protection#88e0ede4e4e7c8f9e1fbe3e1fca6e7faef
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/introduction-course/
- [x] id #056d6069696a45746c766e6c712b6a7762 not found	https://qiskit.org/cdn-cgi/l/email-protection#056d6069696a45746c766e6c712b6a7762
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/events/
- [x] id #9cf4f9f0f0f3dcedf5eff7f5e8b2f3eefb not found	https://qiskit.org/cdn-cgi/l/email-protection#9cf4f9f0f0f3dcedf5eff7f5e8b2f3eefb
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/legacy-content/
- [x] id #b8d0ddd4d4d7f8c9d1cbd3d1cc96d7cadf not found	https://qiskit.org/cdn-cgi/l/email-protection#b8d0ddd4d4d7f8c9d1cbd3d1cc96d7cadf
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/providers/
- [x] 404	https://docs.nvidia.com/cuda/cuquantum/custatevec/index.html
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate
- [x] id #e9818c858586a998809a82809dc7869b8e not found	https://qiskit.org/cdn-cgi/l/email-protection#e9818c858586a998809a82809dc7869b8e

https://qiskit.org/learn/course/basics-quantum-information/
- [x] id #2149444d4d4e615048524a48550f4e5346 not found	https://qiskit.org/cdn-cgi/l/email-protection#2149444d4d4e615048524a48550f4e5346
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/course/algorithm-design/
- [x] id #7b131e1717143b0a120810120f5514091c not found	https://qiskit.org/cdn-cgi/l/email-protection#7b131e1717143b0a120810120f5514091c
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/summer-school/quantum-simulation-summer-school-2022/
- [x] id #533b363f3f3c13223a20383a277d3c2134 not found	https://qiskit.org/cdn-cgi/l/email-protection#533b363f3f3c13223a20383a277d3c2134
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/summer-school/quantum-computing-and-quantum-learning-2021/
- [x] 404	http://mmrc.amss.cas.cn/tlb/201702/W020170224608149940643.pdf
- [x] 404	https://learn.qiskit.org/course/ch-appendix/an-introduction-to-linear-algebra-for-quantum-computing
- [x] id #8ce4e9e0e0e3ccfde5ffe7e5f8a2e3feeb not found	https://qiskit.org/cdn-cgi/l/email-protection#8ce4e9e0e0e3ccfde5ffe7e5f8a2e3feeb
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

https://qiskit.org/learn/summer-school/introduction-to-quantum-computing-and-quantum-hardware-2020/
- [x] 404	https://learn.qiskit.org/course/ch-appendix/an-introduction-to-linear-algebra-for-quantum-computing
- [x] id #94fcf1f8f8fbd4e5fde7fffde0bafbe6f3 not found	https://qiskit.org/cdn-cgi/l/email-protection#94fcf1f8f8fbd4e5fde7fffde0bafbe6f3
- [x] id #become-an-advocate not found	https://qiskit.org/advocates#become-an-advocate

**Comment by eddybrando** [comment]
I believe that the "https://qiskit.org/cdn-cgi/l/email-protection" links reported are just the Qiskit contact email being protected by our CDN, so they are false positives. I'll mark them all as completed since I don't think that we need to change them.

@paaragon maybe we can update our script to avoid reporting emails. What do you think?

**Comment by paaragon** [comment]
> I believe that the "https://qiskit.org/cdn-cgi/l/email-protection" links reported are just the Qiskit contact email being protected by our CDN, so they are false positives. I'll mark them all as completed since I don't think that we need to change them.
> 
> @paaragon maybe we can update our script to avoid reporting emails. What do you think?

Sure! here is [the PR with the change](https://github.com/Qiskit/qiskit.org/pull/3483)
