### ISSUE TITLE
As a maintainer of the documentation page, I want to investigate the spike of 404 pages in documentation, so that I can understand why it's happening and ideally come up with an action plan.

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#3498]
The was a recent spike in the amount of 404 pages reported in our documentation. We need to investigate this together with @Eric-Arellano and fix it asap.

```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/qiskit.org/issues/3500
- [ ] https://github.com/Qiskit/qiskit.org/issues/3501
- [ ] https://github.com/Qiskit/qiskit.org/issues/3502
```
