### ISSUE TITLE
As an event organizer, I want to have a page for the qiskit fall fest 2023, so that we can show the info to the user

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3516]
The Qiskit fall fest 2023 is coming so we need to create a page for it

```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/qiskit.org/issues/3517
- [ ] https://github.com/Qiskit/qiskit.org/issues/3518
- [ ] https://github.com/Qiskit/qiskit.org/issues/3519
- [ ] https://github.com/Qiskit/qiskit.org/issues/3520
```
