### ISSUE TITLE
Remove content replaced by new Learning Platform

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#3557]
With the introduction of the new Learning Platform, we need to make some changes to qiskit.org to remove and update some content.

For this, we need to merge https://github.com/Qiskit/qiskit.org/pull/3423, where most of the work is already done.

### Tasks

- [x] Review the current feature branch PR and, if necessary, make updates for it to be merge-ready
- [x] Prepare related redirections (PR 6241 in the corresponding repo)
- [ ] Push the changes to production on a day specified offline
- [ ] Activate redirections on a day specified offline

**Comment by eddybrando** [comment]
The PR https://github.com/Qiskit/qiskit.org/pull/3423 for the feature branch [feat/sunset-learn-01](https://github.com/Qiskit/qiskit.org/tree/feat/sunset-learn-01) originally included the following list of tasks:

- https://github.com/Qiskit/qiskit.org/issues/3418
- https://github.com/Qiskit/qiskit.org/issues/3410
- https://github.com/Qiskit/platypus/issues/2158
- https://github.com/Qiskit/qiskit.org/issues/3408
- https://github.com/Qiskit/qiskit.org/issues/3409
- https://github.com/Qiskit/qiskit.org/issues/3422

I'll be going through this list and checking if all of them are up-to-date because some changes has been made to qiskit.org since this feature branch started.
