### ISSUE TITLE
Prepare the page for 29th Nov

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit.org#3580]
### Acceptance criteria

We need all the tasks on a PR to merge everything together by Nov 29th

```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/web-components/issues/242
- [ ] https://github.com/Qiskit/qiskit.org/issues/3582
- [ ] https://github.com/Qiskit/qiskit.org/issues/3583
- [ ] https://github.com/Qiskit/qiskit.org/issues/3585
- [ ] https://github.com/Qiskit/qiskit.org/issues/3584
- [ ] https://github.com/Qiskit/qiskit.org/issues/3581
- [ ] https://github.com/Qiskit/qiskit.org/issues/3586
- [ ] https://github.com/Qiskit/qiskit.org/issues/3597
```
