### ISSUE TITLE
Meta: Apply BEM to components

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#489]
From #271:

> Let's try BEM without removing scoped when possible and being flexible with the inner hierarchies, trying not to over-componentize.

**Comment by y4izus** [comment]
There are several name conventions to write BEM. We should be aligned with one of them in order to be consistent everywhere in the code.
[Here](https://en.bem.info/methodology/naming-convention/) you can read more about that. 
For me, using the classic convention could be a good choice. What do you think @delapuente ?

**Comment by delapuente** [comment]
I think it is a good starting point although I prefer the double hyphen style we are already following (in the cases we are using BEM). In my opinion, it makes it more clear the separation between modifiers and elements.

Is there any reason we should avoid the double hyphen form, @y4izus ?

**Comment by y4izus** [comment]
[Here](https://en.bem.info/methodology/naming-convention/#two-dashes-style) we can read:
> Important: A double hyphen inside a comment (--) may cause an error during validation of an HTML document.

I know the probability to have this is small, but I prefer to avoid this "may cause an error" having (_) instead of (--)

**Comment by lerongil** [comment]
Influenced by issue #473 and to be split up into a smaller issue for this sprint.

**Comment by delapuente** [comment]
Right, although only in the cases when it can fail are those where the class contains [characters such as `!`, `>` or `<`](https://html.spec.whatwg.org/multipage/syntax.html#comments) which is very, very unlikely. Considering this, I'll be fine with whatever you decide.

**Comment by y4izus** [comment]
Issues involved:
- [ ] Apply BEM to CompactFeature component #542 
- [ ] Apply BEM to AdvocateCard component #543
- [ ] Apply BEM to LegacyPresentation component #544
- [ ] Apply BEM to ExperimentCard component #545
- [ ] Apply BEM to ExperimentCarousel component #546
- [ ] Apply BEM to ExperimentHeader component #547
- [ ] Apply BEM to QiskitOrgMenu component #548
- [ ] Apply BEM to LinkList component #549
- [ ] Apply BEM to LegacySection component #550
- [ ] Apply BEM to PageSection component #551
- [ ] Apply BEM to Media component #552
- [ ] Apply BEM to SoftwareStack component #553
- [ ] Apply BEM to SyntaxHighlight component #554

**Comment by delapuente** [comment]
Thank you a lot for taking the time of splitting this issue.
